name: Run Data Preprocessing

on:
  push:
    paths:
      - 'preprocessing/**'
      - 'diabetes_prediction_dataset.csv'
  workflow_dispatch:

jobs:
  run-preprocessing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9.13

    - name: Install Dependencies
      run: |
        pip install pandas scikit-learn

    - name: Run Preprocessing Script
      run: |
        python preprocessing/automated_merri.py

    - name: Commit and Push Processed Dataset to Repository
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add preprocessing/diabetes_prediction_dataset.csv
        git diff --cached --quiet || git commit -m "🔄 Auto update: processed dataset"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Processed Dataset as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: cleaned-diabetes
        path: preprocessing/diabetes_prediction_dataset.csv
